name: DevContainer CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and run dev container
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/happypathway/template-python-dev
        runCmd: |
          # Verify the environment
          echo "=== Environment Check ==="
          python --version
          pip list
          
          # Install the package in development mode
          pip install -e .
          
          # Start Redis server for integration tests
          echo "=== Setting up Redis ==="
          sudo service redis-server start
          redis-cli ping
          
          # Check if Redis is running properly
          echo "=== Checking Redis Connection ==="
          # Use the Redis check script
          bash setup/check_redis.sh
          
          REDIS_PING=$(redis-cli ping)
          if [ "$REDIS_PING" != "PONG" ]; then
            echo "Redis is not responding properly"
            echo "Attempting to restart Redis..."
            sudo service redis-server restart
            sleep 2
            redis-cli ping
          else
            echo "Redis is responding correctly"
          fi
          
          # Run tests
          echo "=== Running Unit Tests ==="
          pytest tests/utils --cov=utils
          
          echo "=== Running Integration Tests ==="
          pytest tests/integration --cov=utils --cov-append --timeout=30
