name: Publish to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version_increment:
        description: 'Version increment (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Cache Dev Container data
      uses: actions/cache@v4
      with:
        path: .devcontainer-cache
        key: ${{ runner.os }}-devcontainer-${{ hashFiles('.devcontainer/**') }}
        restore-keys: |
          ${{ runner.os }}-devcontainer-

    - name: Build and test in dev container
      uses: devcontainers/ci@v0.3
      with:
        configFile: .devcontainer/devcontainer.json
        userDataFolder: ".devcontainer-cache"
        imageName: ghcr.io/${{ github.repository }}/devcontainer
        imageTag: ${{ github.ref_name }}
        runCmd: |
          pip install build twine pytest wheel setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pytest tests/
    
    - name: Build and package
      run: |
        python -m build
    
    - name: Verify package
      run: |
        python -m twine check dist/*
    
    - name: Publish package to PyPI
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@v1.8.11
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
    
    - name: Publish package to TestPyPI
      if: github.event_name == 'workflow_dispatch'
      uses: pypa/gh-action-pypi-publish@v1.8.11
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
